version: '3'
services:
  php:
    image: php:7.2

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}

  nginx:
    image: nginx:1.15
    ports:
      - "8100:80"

